name: Deploy a Ninja Hosting

on:
  push:
    branches:
      - develop  # Cambiamos main por develop

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        ref: develop # Asegura que haga el checkout de la rama correcta

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ 
        server-dir: ./public_html/